from collections.abc import Sequence
from datetime import datetime
from typing import Protocol, TypeVar
from uuid import UUID

from memv.models import Episode, Message, SemanticKnowledge

T = TypeVar("T")


# ── Store protocols ──────────────────────────────────────────────────────────


class MessageStore(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def add(self, message: Message) -> None: ...
    async def get(self, message_id: UUID | str) -> Message | None: ...
    async def get_by_user(self, user_id: str) -> list[Message]: ...
    async def get_by_time_range(self, user_id: str, start: datetime, end: datetime) -> list[Message]: ...
    async def list_users(self) -> list[str]: ...
    async def count(self, user_id: str | None = None) -> int: ...
    async def delete(self, message_id: UUID | str) -> bool: ...
    async def clear_user(self, user_id: str) -> int: ...


class EpisodeStore(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def add(self, episode: Episode) -> None: ...
    async def get(self, episode_id: UUID | str) -> Episode | None: ...
    async def get_by_user(self, user_id: str) -> list[Episode]: ...
    async def get_by_time_range(self, user_id: str, start_time: datetime, end_time: datetime) -> list[Episode]: ...
    async def count(self, user_id: str | None = None) -> int: ...
    async def delete(self, episode_id: UUID | str) -> bool: ...
    async def clear_user(self, user_id: str) -> int: ...
    async def update(self, episode: Episode) -> bool: ...


class KnowledgeStore(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def add(self, knowledge: SemanticKnowledge) -> None: ...
    async def get(self, knowledge_id: UUID | str) -> SemanticKnowledge | None: ...
    async def get_by_episode(self, episode_id: UUID | str) -> list[SemanticKnowledge]: ...
    async def list_by_user(
        self, user_id: str, limit: int = 50, offset: int = 0, include_expired: bool = False
    ) -> list[SemanticKnowledge]: ...
    async def count_by_user(self, user_id: str, include_expired: bool = False) -> int: ...
    async def invalidate(self, knowledge_id: UUID | str) -> bool: ...
    async def invalidate_with_successor(self, knowledge_id: UUID | str, successor_id: UUID | str) -> bool: ...
    async def delete(self, knowledge_id: UUID | str) -> bool: ...
    async def clear_by_episodes(self, episode_ids: Sequence[UUID | str]) -> int: ...
    async def clear_user(self, user_id: str) -> int: ...


# ── Index protocols ──────────────────────────────────────────────────────────


class VectorIndex(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def add(self, uuid: UUID, embedding: list[float], user_id: str) -> None: ...
    async def search(self, query_embedding: list[float], top_k: int = 10, user_id: str | None = None) -> list[UUID]: ...
    async def search_with_scores(
        self, query_embedding: list[float], top_k: int = 10, user_id: str | None = None
    ) -> list[tuple[UUID, float]]: ...
    async def has_near_duplicate(self, embedding: list[float], user_id: str, threshold: float) -> tuple[bool, float]: ...
    async def delete(self, uuid: UUID) -> bool: ...
    async def clear_user(self, user_id: str) -> int: ...


class TextIndex(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def add(self, uuid: UUID, text: str, user_id: str) -> None: ...
    async def search(self, query: str, top_k: int = 10, user_id: str | None = None) -> list[UUID]: ...
    async def delete(self, uuid: UUID) -> bool: ...
    async def clear_user(self, user_id: str) -> int: ...


# ── Client protocols ─────────────────────────────────────────────────────────


class EmbeddingClient(Protocol):
    async def embed(self, text: str) -> list[float]: ...
    async def embed_batch(self, texts: list[str]) -> list[list[float]]: ...


class LLMClient(Protocol):
    async def generate(self, prompt: str) -> str: ...
    async def generate_structured(self, prompt: str, response_model: type[T]) -> T: ...
